 <?php $this->headLink()->appendStylesheet($this->basePath() . '/public/css/morris.css') ?>
 <?php echo $this->headScript()
 			->appendFile($this->basePath() . '/public/js/plugins/raphael.min.js')
            ->appendFile($this->basePath() . '/public/js/plugins/morris.min.js')
            ->appendFile($this->basePath() . '/public/js/plugins/morris-data.js')
        ; ?>
 <div class="row">
 	<div class="col-lg-12">
 	    <div class="panel panel-default">
 	        <div class="panel-heading">
 	            Ejemplo 1
 	        </div>
 	        <!-- /.panel-heading -->
 	        <div class="panel-body">
 	            <div id="morris-area-chart"></div>
 	        </div>
 	        <!-- /.panel-body -->
 	    </div>
 	    <!-- /.panel -->
 	</div>

 	<div class="col-lg-6">
 	    <div class="panel panel-default">
 	        <div class="panel-heading">
 	            Bar Chart Example
 	        </div>
 	        <!-- /.panel-heading -->
 	        <div class="panel-body">
 	            <div id="morris-donut-chart"></div>
 	        </div>
 	        <!-- /.panel-body -->
 	    </div>
 	    <!-- /.panel -->
 	</div>	
 </div>
 