<div class="col-lg-12" style="margin-bottom:20px">
    <button type="button" class="btn btn-primary" onclick="modalCrearEmpleado()">Agregar empleado</button>    
</div>
<div class="col-sm-6" id="divTablaEmpleados">
       
</div>
<div class="modal fade" id="modalCrearEmpleado" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Empleados</h4>
      </div>
      <div class="modal-body" id="crearEmpleadoBody">
        
      </div>
      <div class="modal-footer" id="crearEmpleadoFooter">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" onclick="guardarEmpleado()">Guardar cambios</button>
      </div>
    </div>
  </div>
</div>
<script>
$(document).ready(function() {
  listaEmpleados();
});
    function listaEmpleados() {
      $.ajax({
                type: "GET",
                url: "<?php echo $this->basePath() ?>/empleados/listaempleados",
                dataType: "html",
                beforeSend: function() {
                  $("#divTablaEmpleados").html('<div class="progress"><div class="progress-bar progress-bar-striped active"  role="progressbar" style="width: 100%"></div></div>');
                },
                success: function(data) {
                        $("#divTablaEmpleados").html(data);
                      },
                error: function(data){
                    alert('Error');
                }
        });
    }

    function modalCrearEmpleado(){
        $.ajax({
                type: "GET",
                url: "<?php echo $this->basePath() ?>/empleados/nuevoempleado",
                dataType: "html",
                beforeSend: function() {
                  $('#modalCrearEmpleado').modal('show');
                  $("#crearEmpleadoBody").html('<div class="progress"><div class="progress-bar progress-bar-striped active"  role="progressbar" style="width: 100%"></div></div>');
                },
                success: function(data) {
                        $("#crearEmpleadoBody").html(data);
                      },
                error: function(data){
                    alert('Error');
                }
        });
    }
    function modalEditarEstacion(idEmpleado){
        $.ajax({
                type: "GET",
                url: "<?php echo $this->basePath() ?>/empleados/crearempleado/"+idEmpleado,
                dataType: "html",
                beforeSend: function() {
                  $('#modalCrearEmpleado').modal('show');
                  $("#crearEmpleadoBody").html('<div class="progress"><div class="progress-bar progress-bar-striped active"  role="progressbar" style="width: 100%"></div></div>');
                },
                success: function(data) {
                        $("#crearEmpleadoBody").html(data);
                      },
                error: function(data){
                    alert('Error');
                }
        });
    }
    
</script>