<?php 
	$form->setAttribute('action', $this->url('empleados', array('action'=>'nuevoempleado')))
     ->prepare();

?>
<div class="col-lg-12" style="float:none">
	<?php echo $this->form()->openTag($form); ?>
	<div class="row form-group">
		<div class="col-lg-12">
			<?php echo $this->formRow($form->get('NOMBRE')); ?>	
		</div>
	</div>
	<div class="row form-group">
		<div class="col-lg-6">
			<?php echo $this->formRow($form->get('APELLIDO_PATERNO')); ?>
		</div>
		<div class="col-lg-6">
			<?php echo $this->formRow($form->get('APELLIDO_MATERNO')); ?>
		</div>
	</div>
	<div class="row form-group">
		<div class="col-lg-6">
			<?php echo $this->formRow($form->get('NUMERO')); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6" style="margin-top:25px">
			<?php echo $this->formRow($form->get('LUNES')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('I_LUNES')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('F_LUNES')); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6" style="margin-top:25px">
			<?php echo $this->formRow($form->get('MARTES')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('I_MARTES')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('F_MARTES')); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6" style="margin-top:25px">
			<?php echo $this->formRow($form->get('MIERCOLES')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('I_MIERCOLES')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('F_MIERCOLES')); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6" style="margin-top:25px">
			<?php echo $this->formRow($form->get('JUEVES')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('I_JUEVES')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('F_JUEVES')); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6" style="margin-top:25px">
			<?php echo $this->formRow($form->get('VIERNES')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('I_VIERNES')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('F_VIERNES')); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6" style="margin-top:25px">
			<?php echo $this->formRow($form->get('SABADO')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('I_SABADO')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('F_SABADO')); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6" style="margin-top:25px">
			<?php echo $this->formRow($form->get('DOMINGO')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('I_DOMINGO')); ?>
		</div>
		<div class="col-sm-3">
			<?php echo $this->formRow($form->get('F_DOMINGO')); ?>
		</div>
	</div>

</div>
<div class="progress" style="display:none" id="barraCargando">
  <div class="progress-bar progress-bar-striped active"  role="progressbar" style="width: 100%">
  </div>
</div>
<script>
$(document).ready(function(){
	$("#LUNES").val('1');
});
	function guardarEmpleado () {
		$.ajax({
                type: "POST",
                url: "<?php echo $this->basePath() ?>/empleados/nuevoempleado/<?php if ($id) {echo $id;} ?>",
                dataType: "json",
           		data: $('#empleados').serialize(),
           		beforeSend: function() {
                 $('#barraCargando').css('display','block');
                },
                success: function(data) {
                  $('#modalCrearEmpleado').modal('hide');
                  listaEmpleados();  
                },
                error: function(data){
                    alert('Error');
                }
        });
	}

	$('.check').click(function(){
		var dia = $(this).attr('id');
		if($(this).val() == true ) {
			$('#I_'+dia).val('09:00:00');
			$('#F_'+dia).val('18:00:00');	
		} else if($(this).val() == false ) {
			$('#I_'+dia).val('07:00:00');
			$('#F_'+dia).val('11:00:00');	
		}
		
	});
</script>