<?php 
	$form->setAttribute('action', $this->url('empleados', array('action'=>'nuevoempleado')))
     ->prepare();

?>
<div class="col-lg-12" style="float:none">
	<?php echo $this->form()->openTag($form); ?>
	<div class="row form-group">
		<div class="col-lg-12">
			<?php echo $this->formRow($form->get('NOMBRE')); ?>	
		</div>
	</div>
	<div class="row form-group">
		<div class="col-lg-6">
			<?php echo $this->formRow($form->get('APELLIDO_PATERNO')); ?>
		</div>
		<div class="col-lg-6">
			<?php echo $this->formRow($form->get('APELLIDO_MATERNO')); ?>
		</div>
	</div>
	<div class="row form-group">
		<div class="col-lg-6">
			<?php echo $this->formRow($form->get('NUMERO')); ?>
		</div>
		
	</div>
	
</div>
<div class="progress" style="display:none" id="barraCargando">
  <div class="progress-bar progress-bar-striped active"  role="progressbar" style="width: 100%">
  </div>
</div>
<script>

	function guardarEmpleado () {
		$.ajax({
                type: "POST",
                url: "<?php echo $this->basePath() ?>/empleados/nuevoempleado/",
                dataType: "json",
           		data: $('#empleados').serialize(),
           		beforeSend: function() {
                 $('#barraCargando').css('display','block');
                },
                success: function(data) {
                  $('#modalCrearEmpleado').modal('hide');
                  listaEmpleado();  
                },
                error: function(data){
                    alert('Error');
                }
        });
	}
</script>