<?php echo $this->doctype(); ?>
<?php 
if (defined('RUNNING_FROM_ROOT')) {
  $basePath = $this->basePath();
  $this->plugin('basePath')->setBasePath($this->basePath().'/public');
} ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-footer.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img width="75px" src="<?php echo $this->basePath() ?>/img/autolock.png"> AutoLock </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav" style="margin-left:45px">
                        <?php if (!$this->identity()) { ?>
                            <li><a href="<?php echo $basePath ?>/user/login">Iniciar Sesión</a></li>
                            <li><a href="<?php echo $basePath ?>/user/register">Registrarse</a></li>
                        <?php } else { ?>
                            <li><a href="<?php echo $basePath ?>/estaciones"><span class="glyphicon glyphicon-hdd"></span> Mis Estaciones</a></li>
                            <li><a href="<?php echo $basePath ?>/empleados"><span class="glyphicon glyphicon-user"></span> Mis Empleados</a></li>
                            <li><a href="<?php echo $basePath ?>/estadisticas"><span class="glyphicon glyphicon-stats"></span> Estadísticas</a></li>
                            <?php } ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?php echo $this->basePath() ?>/user/logout"><span class="glyphicon glyphicon-lock"></span> Cerrar Sesión</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <div class="footer">
            <div class="container">
                <p class="text-muted">&copy; 2005 - <?php echo date('Y') ?> AutoLock. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </div>
         <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
