<?php 
	echo $this->headLink()
           	->appendStylesheet($this->basePath() . '/public/js/chosen/chosen.min.css');
	echo $this->headScript()
			->appendFile($this->basePath() . '/public/js/chosen/chosen.jquery.js');
	$form->setAttribute('action', $this->url('estaciones', array('action'=>'crearestacion')))
     ->prepare();

?>
<div class="col-lg-12" style="float:none">
	<?php echo $this->form()->openTag($form); ?>
	<div class="row form-group">
		<div class="col-lg-12">
			<?php echo $this->formRow($form->get('NOMBRE')); ?>	
		</div>
	</div>
	<div class="row form-group">
		<div class="col-lg-6">
			<?php echo $this->formRow($form->get('LATITUD')); ?>
		</div>
		<div class="col-lg-6">
			<?php echo $this->formRow($form->get('LONGITUD')); ?>
		</div>
	</div>
	<div class="row form-group">
		<div class="col-lg-6">
			<?php echo $this->formRow($form->get('LATITUD2')); ?>
		</div>
		<div class="col-lg-6">
			<?php echo $this->formRow($form->get('LONGITUD2')); ?>
		</div>	
	</div>
	<div class="row form-group">
		<div class="col-xs-12">
			<label>Empleados con acceso a la estación:</label>
			<?php echo $this->formRow($form->get('USUARIOS')); ?>	
		</div>
	</div>
</div>
<div class="progress" style="display:none" id="barraCargando">
  <div class="progress-bar progress-bar-striped active"  role="progressbar" style="width: 100%">
  </div>
</div>
<script>
 $(document).ready(function() {
 	$('#sUsuarios').chosen();
 });
	function guardarEstacion () {
		$.ajax({
                type: "POST",
                url: "<?php echo $this->basePath() ?>/estaciones/crearestacion/<?php echo $idEstacion; ?>",
                dataType: "json",
           		data: $('#estaciones').serialize(),
           		beforeSend: function() {
                 $('#barraCargando').css('display','block');
                },
                success: function(data) {
                  $('#modalCrearEstacion').modal('hide');
                  listaEstaciones();  
                },
                error: function(data){
                    alert('Error');
                }
        });
	}
</script>