<table class="table">
  <thead>
    <th>Estación</th>
    <th>Estado</th>
  </thead>
  <tbody>
    <?php foreach ($estaciones as $estacion) { ?>
        <tr>
          <td><?php echo $estacion['NOMBRE']; ?></td>
          <td><?php if($estacion['ESTADO']) { ?>
          <span class="label label-success">Activo</span>
          <?php } else { ?>
          <span class="label label-danger">Inactivo</span>
          <?php } ?>
          <span class="glyphicon glyphicon-edit" style="color:dodgerblue;float:right;cursor:pointer" onclick="modalEditarEstacion(<?php echo $estacion['ID'] ?>)"></span></td>
        </tr>
    <?php } ?>
  </tbody>
</table> 